version: '3.8'
services:
  web:
    build: .
    command: python /code/BookStore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/BookStore
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
